name: 'Create Release'

on:
  workflow_call:
    #Secrets are inherited.  Workflows that call reusable workflows in the same organization or enterprise can use the inherit keyword to implicitly pass the secrets.

jobs:
  release:
    name: 'Create Release'
    runs-on: ubuntu-20.04
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance    
    steps:

      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0 #shallow clone
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install node modules
        run: |
          npm install npx semantic-release
          npm install @semantic-release/git @semantic-release/changelog
      - name: 'Create Release'
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE }} #custom PAT with repo scope needed to operate on protected branches
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}         